### ISSUE TITLE
issue on running the experiment.py

### ISSUE THREAD

**Issue by jjin3** [thomwiggers/kemtls-experiment#11]
Hi Thom,
I tried to compile the experiment.py in the measuring/scripts folder and it says "no data from the server" in red. Any idea on how to fix this problem?

Thank you,
Jennifer

**Comment by thomwiggers** [comment]
I'm afraid that it's going to be hard to answer that question without some extra context. Can you provide the full backtraces? It's probably also a good idea to check the setup: have you updated `/etc/hosts` and run `setup_ns.sh`?


I'm afraid that I'm on vacation, so it might be a while before I can get back to you.

**Comment by jjin3** [comment]
Thank you, Thom. 
Yes, I updated /etc/hosts and run setup_n.sh before running the experiment.py file. 
When I run the experiment.py with a sudo command, it shows as follows. 
![image](https://user-images.githubusercontent.com/22776684/171624664-2d7c6921-23a5-45b2-80fa-01fa2e39ddeb.png)

![image](https://user-images.githubusercontent.com/22776684/171624440-a8fb02e4-0d0a-4dc3-b214-28f976068c95.png)

**Comment by thomwiggers** [comment]
`InvalidDNSNameError` suggests `tlsclient` might be called with a ip address rather than a hostname. Have you made any changes to `experiment.py`?

**Comment by jjin3** [comment]
No. I did not change any of the python files or .sh files in the package.

**Comment by thomwiggers** [comment]
I was on vacation; sorry for the delay.

After checking if you still get the error, can you post the output of the following commands? If you've rebooted the box you'll need to re-apply `setup_ns.sh`.

By the way, you should run the scripts in this repository with `sudo`.

```
grep servername /etc/hosts
ip netns list
```

**Comment by thomwiggers** [comment]
I'm closing this issue because I don't have anything actionable right now, but don't hesitate to reach out if you're still having trouble and want to get this to work.
