### ISSUE TITLE
Problem when run cargo

### ISSUE THREAD

**Issue by TunZhou** [thomwiggers/kemtls-experiment#13]
Hi
I have got a problem when run `cargo run --example tlsserver -- --help`

Compiling oqs-sys v0.6.0 (https://github.com/thomwiggers/liboqs-rust.git?branch=dirty-oqs-avx2-rainbow#7356ebc9)
Compiling docopt v1.1.1
error: failed to run custom build command for `oqs-sys v0.6.0 (https://github.com/thomwiggers/liboqs-rust.git?branch=dirty-oqs-avx2-rainbow#7356ebc9)`

Caused by:
  process didn't exit successfully: `/home/abc/kemtls-experiment/rustls/target/debug/build/oqs-sys-3702b637f225cfaa/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=crypto
  cargo:rerun-if-env-changed=OPENSSL_ROOT_DIR
 
Thanks!

**Comment by thomwiggers** [comment]
I suspect that you are seeing issues with the compilation of the C code in liboqs. You might try specifying `CMAKE_C_FLAGS=-Wno-error`, or specifying `CC=clang`, but unfortunately the `reimplementation` branch is a little bit rusty.

Worst case, you should be able to compile everything in docker containers, as is done in the `Dockerfile`.

**Comment by thomwiggers** [comment]
You may be more successful with the recently-uploaded `thesis` branch.

**Comment by TunZhou** [comment]
When I updated it and ran it again, I had a similar problem：

   Compiling sct v0.6.1
   Compiling ct-logs v0.7.0
   Compiling oqs-sys v0.7.99 (https://github.com/thomwiggers/liboqs-rust.git?branch=dirty-thesis-benchmarks#88189321)
   Compiling secsidh-sys v0.1.0 (/home/abc/kemtls-experiment/secsidh-rs/secsidh-sys)
   Compiling docopt v1.1.1
The following warnings were emitted during compilation:

warning: Using SECSIDH_ARITHMETIC=4 (GMP Karatsuba)

error: failed to run custom build command for `secsidh-sys v0.1.0 (/home/abc/kemtls-experiment/secsidh-rs/secsidh-sys)`

Caused by:
  process didn't exit successfully: `/home/abc/kemtls-experiment/rustls/target/debug/build/secsidh-sys-ce20c634255beee0/build-script-build` (exit status: 101)
  --- stdout
  cargo:warning=Using SECSIDH_ARITHMETIC=4 (GMP Karatsuba)
  cargo:rustc-link-lib=gmp
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  
  
  **and**
  gmake[2]: *** [CMakeFiles/Makefile2:1124: src/CMakeFiles/fp-5119m46l244.dir/all] Error 2
  gmake[2]: *** [CMakeFiles/Makefile2:1544: src/CMakeFiles/fp-8191m78l338.dir/all] Error 2
  gmake[1]: *** [CMakeFiles/Makefile2:553: CMakeFiles/secsidh.dir/rule] Error 2
  gmake: *** [Makefile:179: secsidh] Error 2
  thread 'main' panicked at /home/abc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 2

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

How do I fix this or can I just use Dockerfile

**Comment by TunZhou** [comment]
I have resolved this issue by updating gmp.h
