### ISSUE TITLE
Cmake exit

### ISSUE THREAD

**Issue by SimonRastikian** [thomwiggers/kemtls-experiment#5]
Hello,

After the last chat, I updated my OS to Ubuntu 20.04. Now : 
- gcc version  is 9.3.0
- cmake version 3.20.0
- docker version 19.03.8, build afacb8b7f0
- cargo version 1.51.0 (43b129a20 2021-03-16)
Things should be up to date however there is still a build problem. This is what the terminal outputs : 

Compiling ... (all packages) then there is
Compiling oqs-sys v0.1.0 (/home/simonpc/Documents/kemtls-experiment/oqs-rs/oqs-sys)
error: failed to run custom build command for `oqs-sys v0.1.0 (/home/simonpc/Documents/kemtls-experiment/oqs-rs/oqs-sys)`

Caused by:
  process didn't exit successfully: `/home/simonpc/Documents/kemtls-experiment/rustls-kemtls/rustls-mio/target/debug/build/oqs-sys-6a7f51bcb3780b01/build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-lib=crypto
  running: "cmake" "/home/simonpc/Documents/kemtls-experiment/oqs-rs/oqs-sys/liboqs" "-DOQS_USE_OPENSSL=Yes" "-DCMAKE_INSTALL_PREFIX=/home/simonpc/Documents/kemtls-experiment/rustls-kemtls/rustls-mio/target/debug/build/oqs-sys-1bae2684958a2faa/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Optimized"
  -- Configuring incomplete, errors occurred!
  See also "/home/simonpc/Documents/kemtls-experiment/rustls-kemtls/rustls-mio/target/debug/build/oqs-sys-1bae2684958a2faa/out/build/CMakeFiles/CMakeOutput.log".

  --- stderr
  CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 1

  build script failed, must exit now', /home/simonpc/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.45/src/lib.rs:894:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
warning: pqclean/crypto_sign/rainbowIa-cyclic/avx2/blas_comm.c:207:10: warning: ‘gf256mat_solve_linear_eq_ref’ defined but not used [-Wunused-function]
warning:   207 | unsigned gf256mat_solve_linear_eq_ref( uint8_t *sol, const uint8_t *inp_mat, const uint8_t *c_terms, unsigned n ) {
warning:       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: pqclean/crypto_sign/rainbowIa-cyclic/avx2/blas_comm.c:176:10: warning: ‘gf256mat_gauss_elim_ref’ defined but not used [-Wunused-function]
warning:   176 | unsigned gf256mat_gauss_elim_ref( uint8_t *mat, unsigned h, unsigned w ) {
warning:       |          ^~~~~~~~~~~~~~~~~~~~~~~
warning: pqclean/crypto_sign/rainbowIa-cyclic/avx2/blas_comm.c:131:10: warning: ‘gf16mat_solve_linear_eq_ref’ defined but not used [-Wunused-function]
warning:   131 | unsigned gf16mat_solve_linear_eq_ref(uint8_t *sol, const uint8_t *inp_mat, const uint8_t *c_terms, unsigned n) {
warning:       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: pqclean/crypto_sign/rainbowIa-cyclic/avx2/blas_comm.c:103:10: warning: ‘gf16mat_gauss_elim_ref’ defined but not used [-Wunused-function]
warning:   103 | unsigned gf16mat_gauss_elim_ref(uint8_t *mat, unsigned h, unsigned w) {
warning:       |          ^~~~~~~~~~~~~~~~~~~~~~
warning: pqclean/crypto_sign/rainbowIa-cyclic/avx2/blas_comm.c:64:6: warning: ‘gf256mat_prod_ref’ defined but not used [-Wunused-function]
warning:    64 | void gf256mat_prod_ref(uint8_t *c, const uint8_t *matA, unsigned n_A_vec_byte, unsigned n_A_width, const uint8_t *b) {
warning:       |      ^~~~~~~~~~~~~~~~~
warning: pqclean/crypto_sign/rainbowIa-cyclic/avx2/blas_comm.c:54:6: warning: ‘gf16mat_prod_ref’ defined but not used [-Wunused-function]
warning:    54 | void gf16mat_prod_ref(uint8_t *c, const uint8_t *matA, unsigned n_A_vec_byte, unsigned n_A_width, const uint8_t *b) {
warning:       |      ^~~~~~~~~~~~~~~~
warning: pqclean/crypto_sign/rainbowIa-cyclic/avx2/rainbow_keypair_computation.c:369:6: warning: ‘calculate_Q_from_F_cyclic_ref’ defined but not used [-Wunused-function]
warning:   369 | void calculate_Q_from_F_cyclic_ref( cpk_t *Qs, const sk_t *Fs, const sk_t *Ts ) {
warning:       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
warning: pqclean/crypto_sign/rainbowIa-cyclic/avx2/rainbow_keypair_computation.c:304:6: warning: ‘calculate_F_from_Q_ref’ defined but not used [-Wunused-function]
warning:   304 | void calculate_F_from_Q_ref( sk_t *Fs, const sk_t *Qs, sk_t *Ts ) {
warning:       |      ^~~~~~~~~~~~~~~~~~~~~~
warning: pqclean/crypto_sign/rainbowIa-cyclic/avx2/rainbow_keypair_computation.c:187:6: warning: ‘calculate_Q_from_F_ref’ defined but not used [-Wunused-function]
warning:   187 | void calculate_Q_from_F_ref( ext_cpk_t *Qs, const sk_t *Fs, const sk_t *Ts ) {
warning:       |      ^~~~~~~~~~~~~~~~~~~~~~
error: build failed

I checked the CMakeOutput.log file and it is said 
The system is: Linux - 5.8.0-48-generic - x86_64

Do you know what should I be doing to solve this?

**Comment by thomwiggers** [comment]
* CMake is complaining about lack of `make`, so you probably want to run `apt-get install build-essential`.
* The remainder seem warnings that can safely be ignored.

**Comment by SimonRastikian** [comment]
Thank you a lot Thom! After I ran this I discovered I also had clang missing. As you said I did not  pay attention to all the declared but unused functions warnings however some new warning of the type 


warning: allow(unreachable_code) incompatible with previous forbid
   --> /home/simonpc/Documents/kemtls-experiment/webpki/src/webpki.rs:365:25
    |
48  |     warnings,
    |     -------- `forbid` level set here
...
365 |         let algorithm = key_id_to_kem(spki.algorithm_id_value)?;
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ overruled by previous forbid
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #81670 <https://github.com/rust-lang/rust/issues/81670>

is occurring,
however things seem to work and the target/debug/examples/tlsserver --help indeed outputs a help manual.

Thank you again!

**Comment by thomwiggers** [comment]
Yeah, such things happen if you're using Rust — the repo should really be pinned to a particular version of the compiler. Good to hear that it's mostly fixed.
