### ISSUE TITLE
Encoder.py  Problem

### ISSUE THREAD

**Issue by SimonRastikian** [thomwiggers/kemtls-experiment#7]
Hello,

I have compiled the code as you said during the meeting:
I built the tlsserver, and tlsclient - everything seemed okay
However, when I ran the script in measuring, the following error occurred on 
Step 51/60 : RUN      pipenv run python encoder.py

Traceback (most recent call last):
  File "encoder.py", line 459, in <module>
    get_classic_certs()
  File "encoder.py", line 438, in get_classic_certs
    shutil.copyfile("rsas-int/pki/private/client.key", "client.key")
  File "/root/.local/share/virtualenvs/mk-cert-QibA59Jh/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'rsas-int/pki/private/client.key'

I am not sure why is this happening. Could you give me a hint?

Thanks

**Comment by thomwiggers** [comment]
They were accidentally not included as they were covered by the gitignore of the parent directory in mk-cert.

I've pushed updates in 6ebd7e6 and in mk-cert.
