### ISSUE TITLE
Unknown host

### ISSUE THREAD

**Issue by SimonRastikian** [thomwiggers/kemtls-experiment#8]
I was running the measurement file using the script.
This generates the KDDD with client auth DD,  KKDD, KKDD with client auth KD, XRRR, XRRR with client auth RR.
However the code stops with an error:

File ".../kemtls-experiment/measuring/scripts/experiment.py", line 647, in <module>
    hostname = reverse_resolve_hostname()
  File ".../kemtls-experiment/measuring/scripts/experiment.py", line 497, in reverse_resolve_hostname
    return socket.gethostbyaddr("10.99.0.1")[0]
socket.herror: [Errno 1] Unknown host

What should I do to solve this?

**Comment by thomwiggers** [comment]
To run the `experiment.py` scripts, you need `10.99.0.1  servername` in `/etc/hosts`; you also need the ip namespaces set up (there's a script to do the work for you)

**Comment by SimonRastikian** [comment]
Ok this just worked. I had to run the ./setup_ns.sh script then ./setinitcwd.sh 10. Thanks again!

Btw I just found your Hacking in C courses and I am following them :)
