### ISSUE TITLE
Missing rustls-kemtls folder

### ISSUE THREAD

**Issue by radwasherif** [thomwiggers/kemtls-experiment#9]
Hi Thom, 
I am working on a PSK version of the KEMTLS protocol for my master's thesis at ETH Zurich. I would also like to run some experiment on the protocol we designed to compare it to TLS 1.3 in PSK mode and ideally I'd like to re-use your code here. 

In the README file you mention a rustls-kemtls folder where you modify the rustls stack to suit KEMTLS, but I'm not sure I can find that folder in the repo.

**Comment by thomwiggers** [comment]
ah, that got refactored such that the rustls code supports both versions of the protocol.

**Comment by thomwiggers** [comment]
By the way, what's the general idea behind your project? It's cool that so many people are doing followup work.

**Comment by radwasherif** [comment]
We're doing a pre-shared key variant for KEMTLS: designing the protocol, security model, and proving security. I'd be happy to send you a copy of my thesis when it's done.

**Comment by thomwiggers** [comment]
Pre-shared KEM keys? Because that's already implemented: https://eprint.iacr.org/2021/779

**Comment by radwasherif** [comment]
No, not pre-distributed KEM keys, but rather an equivalent of the pre-shared key mode in TLS 1.3, but for KEMTLS.

**Comment by thomwiggers** [comment]
Okay cool, looking forward to seeing your work!
